apiVersion: v1
kind: Namespace
metadata:
  name: $PHR_LIVERPOOL_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${PHR_LIVERPOOL_NAMESPACE}-service-authentication
  namespace: $PHR_LIVERPOOL_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${PHR_LIVERPOOL_NAMESPACE}-service-authentication
  template:
    metadata:
      labels:
        app: phr-${PHR_LIVERPOOL_NAMESPACE}-service-authentication
    spec:
      containers:
      - name: phr-${PHR_LIVERPOOL_NAMESPACE}-service-authentication
        image: ${PHR_REGISTRY}/phr-${PHR_LIVERPOOL_NAMESPACE}-service-authentication:v${BUILD_NUMBER}
        env:
        - name: APP_PORT
          value: '3002'
        - name: NODE_ENV
          value: development
        - name: DATABASE_URL
          value: https://phr-${PHR_LIVERPOOL_NAMESPACE}-service-database:3001
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: JWT_SECRET_KEY
          value: ${PHR_JWT_SECRET_KEY}
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${PHR_LIVERPOOL_NAMESPACE}-service-authentication
  namespace: $PHR_LIVERPOOL_NAMESPACE
spec:
  selector:
    app: phr-${PHR_LIVERPOOL_NAMESPACE}-service-authentication
  ports:
  - port: 3002
