const messageCodes = {
  1001: 'Protected resource, use Authorization header to get access.',
  1002: 'Invalid email/password combination.',
  1003: 'Token generation failed.',
  1004: 'Bad Request : Invalid data provided.',
  1005: 'Sorry you cannot create an account at this time, try again later or with different details.',
  1006: 'User logged in another system.',
  1007: 'Recaptcha failed, please reload the page and try again.',
  1008: 'User not found.',
  1009: 'Data not found.',
  1010: 'Password hash failed.',
  1011: 'Updated successfully.',
  1012: 'Successfully disconnected from care team.',
  1013: 'User logout successfully.',
  1014: 'If your email address exists in our database, you will receive a password reset link at your email address in a few minutes.',
  1015: 'Mail not sent.',
  1016: 'Unable to fetch data.',
  1017: 'Current password does not match.',
  1018: 'Already exist.',
  1019: 'Created successfully.',
  1020: 'Deleted successfully.',
  1021: 'Bad Request : date must be less than current date!.',
  1022: 'Bad Request : Please provide valid data.',
  1023: 'Account Connected!',
  1024: 'Details do not match. Please try again later',
  1025: 'Details do not match. Please Check the given detail',
  1026: 'Given NHS already exists. Please check it!',
  1027: 'Invalid NHS Number.!',
  1028: 'Invalid Token.!',
  1029: 'Please verify your email in order to login to your account',
  1030: 'OTP is invalid',
  1031: 'We are unable to complete your registration at this time. Please contact us at mindwave.portal@nhs.net',
  1032: 'You already got invite from our system. Please check your mail.'
};
module.exports = messageCodes;
