apiVersion: v1
kind: Namespace
metadata:
  name: $PHR_CANDM_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${PHR_CANDM_NAMESPACE}-service-health
  namespace: $PHR_CANDM_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${PHR_CANDM_NAMESPACE}-service-health
  template:
    metadata:
      labels:
        app: phr-${PHR_CANDM_NAMESPACE}-service-health
    spec:
      containers:
      - name: phr-${PHR_CANDM_NAMESPACE}-service-health
        image: ${PHR_REGISTRY}/phr-${PHR_CANDM_NAMESPACE}-service-health:v${BUILD_NUMBER}
        env:
        - name: APP_PORT
          value: '3036'
        - name: DATABASE_URL
          value: https://phr-${PHR_CANDM_NAMESPACE}-service-database:3001
        - name: NODE_ENV
          value: development
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        ports:
        - containerPort: 3036
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${PHR_CANDM_NAMESPACE}-service-health
  namespace: $PHR_CANDM_NAMESPACE
spec:
  selector:
    app: phr-${PHR_CANDM_NAMESPACE}-service-health
  ports:
  - port: 3036
