apiVersion: v1
kind: Service
metadata:
  name: maia-apostrophe
  labels:
    app: maia-apostrophe
spec:
  ports:
    - port: 80
      nodePort: 31663
      protocol: TCP
  selector:
    app: maia-apostrophe
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: maia-apostrophe
  labels:
    app: maia-apostrophe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maia-apostrophe
      tier: frontend
  strategy:
    type: Recreate #TODO: check about this for production https://container-solutions.com/kubernetes-deployment-strategies/
  template:
    metadata:
      labels:
        app: maia-apostrophe
        tier: frontend
    spec:
      imagePullSecrets:
      - name: acr-credentials
      containers:
      - image: opensourceacr.azurecr.io/maia-apostrophe:v21
        name: maia-apostrophe
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: '80'
        - name: MONGO_STRING
          value: mongodb://staginguser:JWffVAlV8o1eM7ig@SG-PHRStagingMongo-15354.servers.mongodirector.com:27017/MAIA?ssl=true
        - name: SERVICE_PHR
          value: https://service-controller:3000
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: CAPTCHA_SITE_KEY
          value: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      ports:
        - containerPort: 80
          name: maia-apostrophe
      imagePullSecrets:
       - name: regcred
