apiVersion: v1
kind: Service
metadata:
  name: apostrophe
  labels:
    app: apostrophe
spec:
  ports:
    - port: 80
      nodePort: 31663
      protocol: TCP
  selector:
    app: apostrophe
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: apostrophe
  labels:
    app: apostrophe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apostrophe
      tier: frontend
  strategy:
    type: Recreate #TODO: check about this for production https://container-solutions.com/kubernetes-deployment-strategies/
  template:
    metadata:
      labels:
        app: apostrophe
        tier: frontend
    spec:
      imagePullSecrets:
      - name: acr-credentials
      containers:
      - image: mindwavephr.azurecr.io/phr-apostrophe:v571
        name: phr-apostrophe
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: '80'
        - name: MONGO_STRING
          value: mongodb://staginguser:JWffVAlV8o1eM7ig@SG-PHRStagingMongo-15354.servers.mongodirector.com:27017/PHR?ssl=true
        - name: SERVICE_PHR
          value: https://service-controller:3000
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: CAPTCHA_SITE_KEY
          value: 6LfWCZAUAAAAANWn35nOXRU-_QRIXp4NVVGs8c2z
        - name: STORAGE_BACKEND
          value: AZURE #AWS or AZURE
        - name: AWS_HTTPS
          value: 'true'
        - name: AWS_SECRET
          value: dp/P9PmGd+b6BhLMbsv10/tqxIakWPcMRvdtWggF
        - name: AWS_KEY
          value: AKIAISSOS642ZZTSWU4A
        - name: AWS_BACKEND
          value: s3
        - name: AWS_BUCKET
          value: mindwave-phr
        - name: AWS_REGION
          value: us-east-1
        - name: AZURE_ACCOUNT
          value: phrapostorage
        - name: AZURE_CONTAINER
          value: phrapostorage
        - name: AZURE_DISABLED_FILE_KEY
          value: xcvsdf890
        - name: AZURE_KEY
          value: pLmQMpwfrefBSHalQRE8JLUkQ42pkVxsUDD2R5vd4r4a7MMnau5xquYgpfzoTG3iS/IKW/yUWlh1cjOuZ9rnTg==
        ports:
        - containerPort: 80
          name: apostrophe
      imagePullSecrets:
       - name: regcred
