apiVersion: v1
kind: Service
metadata:
  name: mc-nhslogin
  labels:
    app: mc-nhslogin
spec:
  ports:
    - port: 80  
      protocol: TCP
  selector:
    app: mc-nhslogin
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mc-nhslogin
  labels:
    app: mc-nhslogin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-nhslogin
      tier: frontend
  strategy:
    type: Recreate #TODO: check about this for production https://container-solutions.com/kubernetes-deployment-strategies/
  template:
    metadata:
      labels:
        app: mc-nhslogin
        tier: frontend
    spec:
      imagePullSecrets:
      - name: acr-credentials      
      containers:
      - image: mindwavephr.azurecr.io/mc-apostrophe:v570
        name: mc-nhslogin
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: '80'
        - name: MONGO_STRING
          value: mongodb://staginguser:JWffVAlV8o1eM7ig@SG-PHRStagingMongo-15354.servers.mongodirector.com:27017/MercyCare?ssl=true
        - name: SERVICE_PHR
          value: https://service-controller:3000
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'          
        - name: CAPTCHA_SITE_KEY
          value: 6LfWCZAUAAAAANWn35nOXRU-_QRIXp4NVVGs8c2z
        - name: NHS_LOGIN_CLIENT_ID
          value: Mersey-PHR
        - name: NHS_LOGIN_REDIRECT_URL
          value: https://nhslogin.healthvr.uk/users/nhslogin
        ports:
        - containerPort: 80
          name: mc-nhslogin
