apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-configuration
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-configuration
    spec:
      imagePullSecrets:
      - name: acr-credentials
      containers:
        - name: service-configuration
          image: mindwavephr.azurecr.io/phr-service-configuration:v755
          env:
          - name: APP_PORT
            value: '2000'
          - name: NODE_ENV
            value: development
          - name: DATABASE_URL
            value: https://service-database:3001
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: '0'
          ports:
            - containerPort: 2000
      imagePullSecrets:
       - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: service-configuration
  labels:
    name: service-configuration
spec:
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP
  selector:
    app: service-configuration
  type: ClusterIP
