apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-authentication
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-authentication
    spec:
      imagePullSecrets:
      - name: acr-credentials
      containers:
        - name: service-authentication
          image: mindwavephr.azurecr.io/phr-service-authentication:v755
          env:
          - name: APP_PORT
            value: '3002'
          - name: NODE_ENV
            value: development
          - name: DATABASE_URL
            value: https://service-database:3001
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: '0'
          - name: JWT_SECRET_KEY
            value: E$Wnh24aO2C06A6Kt#liqgVVz@s77fbR$pSl*mtL!@yYtUEbl*
          ports:
            - containerPort: 3002
      imagePullSecrets:
       - name: regcred            

---
apiVersion: v1
kind: Service
metadata:
  name: service-authentication
  labels:
    name: service-authentication
spec:
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: service-authentication
  type: ClusterIP
