apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-xds
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-xds
    spec:
      imagePullSecrets:
      - name: acr-credentials
      containers:
        - name: service-xds
          image: mindwavephr.azurecr.io/phr-service-xds:v878
          env:
          - name: APP_PORT
            value: '4003'
          - name: DATABASE_URL
            value: https://service-database:3001
          - name: NODE_ENV
            value: development
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: '0'
          ports:
            - containerPort: 4003

---
apiVersion: v1
kind: Service
metadata:
  name: service-xds
  labels:
    name: service-xds
spec:
  ports:
    - port: 4003
      targetPort: 4003
      protocol: TCP
  selector:
    app: service-xds
  type: ClusterIP
