apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-job
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-job
    spec:
      imagePullSecrets:
      - name: acr-credentials
      containers:
        - name: service-job
          image: mindwavephr.azurecr.io/phr-service-job:v755
          env:
          - name: APP_PORT
            value: '3021'
          - name: DATABASE_URL
            value: https://service-database:3001
          - name: NODE_ENV
            value: development
          - name: EMAIL_SERVICE
            value: https://service-email:3020
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: '0'
          ports:
            - containerPort: 3021
      imagePullSecrets:
       - name: regcred            

---
apiVersion: v1
kind: Service
metadata:
  name: service-job
  labels:
    name: service-job
spec:
  ports:
    - port: 3021
      targetPort: 3021
      protocol: TCP
  selector:
    app: service-job
  type: ClusterIP
