


pipeline {
  agent any
  stages {
stage('Build Apostrophe') {
      steps {
        acrQuickTask(azureCredentialsId: "$env.AZURE_SP", local: "client", imageNames: [[image: "liverpoolacr.azurecr.io/phr-Liverpool staging-apostrophe:v$env.BUILD_NUMBER" ], [image: "liverpoolacr.azurecr.io/phr-Liverpool staging-apostrophe apostrophe:latest"]], registryName: "liverpoolacr", resourceGroupName: "liverpoolcamhs-staging")
      }
    }
    stage('Build Controller') {
      steps {
        acrQuickTask(azureCredentialsId: "$env.AZURE_SP", local: "server", imageNames: [[image: "liverpoolacr.azurecr.io/phr-Liverpool staging-service-controller:v$env.BUILD_NUMBER" ], [image: "liverpoolacr.azurecr.io/phr-Liverpool staging-apostrophe-service-controller:latest"]], registryName: "liverpoolacr", resourceGroupName: "liverpoolcamhs-staging" )
      }
    }
  }
}
