pipeline {
  agent any
  stages {
    stage('Build apostrophe') {
      steps {
        acrQuickTask(azureCredentialsId: "$env.AZURE_SP" , local:"client", imageNames: [[image: "$env.PHR_REGISTRY/$env.PHR_LIVERPOOL_NAMESPACE-apostrophe:v$env.BUILD_NUMBER" ], [image: "$env.PHR_REGISTRY/$env.PHR_LIVERPOOL_NAMESPACE-apostrophe:latest"]], registryName: "$env.AZURE_CONTAINER_REGISTRY", resourceGroupName: "$env.AZURE_RG", timeout: 28800)
      }
    }
    stage('Build phr') {
      steps {
        acrQuickTask(azureCredentialsId: "$env.AZURE_SP" , local:"server", imageNames: [[image: "$env.PHR_REGISTRY/$env.PHR_LIVERPOOL_NAMESPACE-phr:v$env.BUILD_NUMBER" ], [image: "$env.PHR_REGISTRY/$env.PHR_LIVERPOOL_NAMESPACE-phr:latest"]], registryName: "$env.AZURE_CONTAINER_REGISTRY", resourceGroupName: "$env.AZURE_RG", timeout: 28800)
      }
    }

    stage('Deployment') {
      parallel {

        stage('Deploy Apostrophe') {
          steps {
           kubernetesDeploy(kubeConfig: [path:"$KUBERNETES_CONFIG"], configs: 'script/production/80_apostrophe.yaml')
         }
       }

        stage('Deploy Phr') {
          steps {
            kubernetesDeploy(kubeConfig: [path:"$KUBERNETES_CONFIG"], configs: 'script/production/3000_controller.yaml')
          }
        }
      }
    }
  }
}
